### ISSUE TITLE
MC 1.14.4 Server crash

### ISSUE THREAD

**Issue by calloatti** [MrMarnic/ExtraBows#10]
https://paste.ee/p/DlqCd

mods folder:

fabric-api-0.3.0+build.207.jar
extrabows-v1.14.4+Fabric+b1.jar

**Comment by Shnupbups** [comment]
The mixin to `TootipContext` needs to be marked as client side only, as that class doesn't exist server side.

**Comment by MrMarnic** [comment]
Thank you. Will be fixed in the next update.

**Comment by MrMarnic** [comment]
Should be fixed in v1.14.4 Fabric b2.
Can you tell me if it works

**Comment by MrMarnic** [comment]
This seems not to be the bug because the error still occurs

**Comment by MrMarnic** [comment]
It is fixed now.
