### ISSUE TITLE
Skeletons do not shoot

### ISSUE THREAD

**Issue by d0kha** [MrMarnic/ExtraBows#11]
I have this mod on mc 1.14.3, the forge version.
The skeletons don't shoot, instead, they attack like a zombie, melee.
I don't know if this should be happening like that, if not please help me with that.

Thank you

**Comment by MrMarnic** [comment]
Have you any other mods installed?
And can you send the game log, please.

**Comment by MrMarnic** [comment]
Which forge version are you using?
