### ISSUE TITLE
Crash on launch MC 1.14.4

### ISSUE THREAD

**Issue by Miss-Mercy** [MrMarnic/ExtraBows#12]
MC version 1.14.4
Forge version 28.0.45

The game crashed whilst rendering overlay
Error: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float

Crash Report:
https://pastebin.com/3LJgsUtd

**Comment by MrMarnic** [comment]
Can you send your modified config file?

**Comment by MrMarnic** [comment]
Fixed in extrabows-v1.14.4 b3
