### ISSUE TITLE
fabric server not launching due to many mod class exceptions(1.14.4)fabric

### ISSUE THREAD

**Issue by SDUBZ** [MrMarnic/ExtraBows#14]
this the issue gist i made with log and mod list etc due to many class conflicts https://gist.github.com/SDUBZ/8a121bddf045e26d7234afb321140f29

**Comment by MrMarnic** [comment]
Is this really a problem with my mod?
Does the game not start with it installed?
Because the log is very messy, but this is not your fault.

**Comment by SDUBZ** [comment]
i updated alot of mods and it fixed most of them so extrabows seems to be working but hard to tell until i can get into the server world now but progress had been made
