### ISSUE TITLE
Crash during startup; Forge 1.14.4

### ISSUE THREAD

**Issue by NyanMC** [MrMarnic/ExtraBows#15]
Minecraft version: Forge 1.14.4 - 28.0.49/ Fabric version

ModLoader version: Forge / Fabric

Mod Version: v1.14.4 forge b2

Short Description: Game Crash on startup

Crash log: https://pastebin.com/mdvXg8Uc

**Comment by MrMarnic** [comment]
Did you modify the config file?

**Comment by NyanMC** [comment]
I didn't touch the config at all, this is a first-time launch crash.

**Comment by MrMarnic** [comment]
Ok. Does the mod work alone?

**Comment by NyanMC** [comment]
I just attempted running the same version of forge with this mod alone, and it does not work. I created another pastebin with the crash report (i doubt it's any different other than the mod list shown)

**Comment by MrMarnic** [comment]
I think it has something to do with the config. I will try to investigate.

**Comment by MrMarnic** [comment]
Fixed in extrabows-v1.14.4 b3
