### ISSUE TITLE
Create localization folder for easy translating

### ISSUE THREAD

**Issue by juanm55** [MrMarnic/ExtraBows#16]
Create a folder or a set of default templates in order for contributors to add the language translations. (These could be json files for easy editing or well whatever format suits you best)

I think this is just easier to maintain than baking the languages in (which I am guessing is what is happening here since I cannot see the folder or the like anywhere)

I could help with Spanish if still needed

**Comment by MrMarnic** [comment]
Thats a good idea. I will do it.

**Comment by MrMarnic** [comment]
And yes I really need Spanish. That would be great. And I have create the template folder.

**Comment by juanm55** [comment]
I cloned the repository, and created a branch on my machine, tried to push it but got a 403 (not allowed to access)

If you want I can just send you the template with the initial translations somewhere or you can just give me the access to push that.

(I just copied the file, edited it with spanish, renamed to template_es.json and that was it though I don't know Java, but I can help with translation if you can use that)

**Comment by MrMarnic** [comment]
Ok thank you. You can send me the files just here or you can create a Pull request

**Comment by juanm55** [comment]
here's the contents of the file::::::::::

{
"item.animalnet.mob_net_small":"Red para monstruo pequeña",
"itemGroup.AnimalNet Items":"Items RedAnimales",
"message.animalnet.formal_animal":"Este animal",
"item.animalnet.animal_net_big":"Red para animal grande",
"message.animalnet.npc_needed":"Necesitas NPC para poder capturarlos!",
"item.animalnet.animal_net_small":"Red para Animal pequeña",
"item.animalnet.animal_net_medium":"Red para Animal Mediana",
"message.animalnet.can_not_be_caught":"Esta entidad no puede ser capturada!",
"message.animalnet.net_too_small":"Necesitas una red más grande!",
"message.animalnet.formal_npc":"Este NPC",
"message.animalnet.formal_mob":"Este Monstruo",
"item.animalnet.mob_core":"Monstruo Core",
"message.animalnet.villager_needed":"Necesitas un NPC para capturar un aldeano!",
"item.animalnet.npc_net":"Red NPC",
"message.animalnet.mob_needed":"Necesitas monstruos para poder capturarlos!",
"item.animalnet.catched_animal":"Animal/Monstruo capturado",
"message.animalnet.animal_needed":"Necesitas una Red para Animal para capturar animales normales!",
"item.animalnet.mob_net_big":"Red para monstruo grande",
"message.animalnet.entity_too_big":"%s es demasiado grande y no puede ser capturado!",
"item.animalnet.spawner_fragmental": "Spawner Fragmental"
}
