### ISSUE TITLE
[Fabric]No showing up in Fabric

### ISSUE THREAD

**Issue by SassinPr0ph3cy** [MrMarnic/ExtraBows#17]
Hi I downloaded the lasted version ExtraBows-v1.14.4 Fabric b2 but nothing is showing up

**Comment by MrMarnic** [comment]
Are the items not in the game?

**Comment by MrMarnic** [comment]
I mean the bows?

**Comment by SassinPr0ph3cy** [comment]
Yes not seeing anything in Game nothing when I go into creative or using fabrics inventory editor (REI).

**Comment by MrMarnic** [comment]
Which Fabric version are you using?

**Comment by SassinPr0ph3cy** [comment]
Minecraft: 1.14.4/Fabric
Fabric: 0.6.1+ Build 165

**Comment by MrMarnic** [comment]
Can you send your game log please.

**Comment by SassinPr0ph3cy** [comment]
[MC-Log.txt](https://github.com/MrMarnic/ExtraBows/files/3579182/MC-Log.txt)
Hoping this is the log.

**Comment by MrMarnic** [comment]
Yes that is the log but no bug is visible.That is strange. Can you open the upgrade inventory for the vanilla bow (B key)

**Comment by SassinPr0ph3cy** [comment]
No trying to open the upgrade  inventory but nothing happens also noticed that ExrtaBows isnt listed within the key bindings in the controls menu.  almost like it isnt installed but its in the mods folder. I dont need any other mods with it do I?

**Comment by MrMarnic** [comment]
Can you maybe send the MultiMC instance?

**Comment by SassinPr0ph3cy** [comment]
Sure hope zippyshare is Okay.. seems file was to big...
https://www58.zippyshare.com/v/9iZ3b8gt/file.html

**Comment by MrMarnic** [comment]
I can not download it is says 403 Forbidden

**Comment by SassinPr0ph3cy** [comment]
odd, try this Mega link hopefully that works...
https://mega.nz/#!tUYERY6R!7hBDYymigUkt4DqU06fKF0Bm_4E2VNm2xLxIpR_NbKY

**Comment by SassinPr0ph3cy** [comment]
Did that link work by any chance?

**Comment by MrMarnic** [comment]
You are using the Forge version not the Fabric one
