### ISSUE TITLE
Game crash, cause unsure

### ISSUE THREAD

**Issue by NyanMC** [MrMarnic/ExtraBows#18]
Minecraft version: Forge 1.14.4  - 28.1.1

ModLoader version: Forge

Mod Version: v1.14.4 b4

Short Description: Game crash, the cause I'm unsure of but it occured when entering a mine (Perhaps a skeleton spawned and it made the game crash? I'm not sure)
If this isn't from your mod I'm sorry for causing a disturbance, the crash log just mentioned extrabows and so I decided to report it here

Crash log: https://pastebin.com/tNT48FWG

**Comment by NyanMC** [comment]
i WAS using the latest forge version but i see you updated the mod so i'll give the new version a try

**Comment by MrMarnic** [comment]
Which exact Forge version where you using?
