### ISSUE TITLE
Game crashes when firing any bow when using extrabows version 1.14.4 b4

### ISSUE THREAD

**Issue by SoumyBhow** [MrMarnic/ExtraBows#19]
I've updated ExtraBows from 1.14.4 b3 to b4 but after that, firing any bow crashes the game. I've tried the Lucky Bow from the Lucky Blocks mod, the Emerald Bow from Extra Bows and the Nether Brick Bow from Patty'sMoreTools, and all crashed the game. I had to downgrade ExtraBows back to b3 to get them to work.

**Comment by MrMarnic** [comment]
Can I send you a test build that you could try out?

**Comment by SoumyBhow** [comment]
Sure.

**Comment by MrMarnic** [comment]
https://www.dropbox.com/s/tjey2a9fs49m475/extrabows-v1.14.4%20b5.jar?dl=1

**Comment by SoumyBhow** [comment]
I tried your test build and this is what happened:
Lucky Bow from Lucky Block mod works
Red Nether Brick Bow from Patty's More Tools works
Diamond and Emerald Bows from Extra Bows crashes the game

**Comment by MrMarnic** [comment]
Can you send the crash log please

**Comment by SoumyBhow** [comment]
Sorry to disappoint, but I'm using Tlauncher... So these are the closest things I could find to crash logs...
[crash-2019-09-13_00.17.11-client.txt](https://github.com/MrMarnic/ExtraBows/files/3611001/crash-2019-09-13_00.17.11-client.txt)
[crash-2019-09-13_12.47.27-server.txt](https://github.com/MrMarnic/ExtraBows/files/3611002/crash-2019-09-13_12.47.27-server.txt)
[crash-2019-09-13_12.49.25-server.txt](https://github.com/MrMarnic/ExtraBows/files/3611003/crash-2019-09-13_12.49.25-server.txt)

**Comment by MrMarnic** [comment]
Ok tank you this should work
https://www.dropbox.com/s/tjey2a9fs49m475/extrabows-v1.14.4%20b5.jar?dl=1

**Comment by MrMarnic** [comment]
Thank you this should work
https://www.dropbox.com/s/lm66pv5j9ekqfbi/extrabows-v1.14.4%20b5.jar?dl=1

**Comment by SoumyBhow** [comment]
Thanks! It works now! I have another question, though. Your Extra Bows menu isn't meant to be opened when holding other bow mods, right?

**Comment by MrMarnic** [comment]
Yes at the moment it can not work with other mods bows

**Comment by SoumyBhow** [comment]
Alright, that's okay. Thank you for your help and time!

**Comment by MrMarnic** [comment]
Then I will upload it.
