### ISSUE TITLE
Skeleton Missing Texture

### ISSUE THREAD

**Issue by Flunder620** [MrMarnic/ExtraBows#2]
The bow's repaced with an untextured block
![2019-07-10_18 29 33](https://user-images.githubusercontent.com/52764608/61011628-01ce2680-a341-11e9-9920-5b9102e8769e.png)

**Comment by MrMarnic** [comment]
Which Minecraft and mod version are you using.

**Comment by Flunder620** [comment]
Minecraft 1.14.3, and mod version v1.14.3 b1 Fabric

**Comment by MrMarnic** [comment]
The error will be fixed in the next version

**Comment by MrMarnic** [comment]
Should be fixed in Extra Bows-v1.14.3 Fabric b2
