### ISSUE TITLE
Bridge Upgrade -> Water and Cliffs

### ISSUE THREAD

**Issue by rapus95** [MrMarnic/ExtraBows#22]
Because the bridge doesn't appear on the line of flight (or at max 2 blocks under the line of flight) you cannot efficiently use the Bridge upgrade to climb cliffs or to build temporary bridges with it. Furthermore it doesn't build blocks in the water thus building a bridge across a river for a horse doesn't work either.

**Comment by MrMarnic** [comment]
So you suggest that the bridge should appeare maybe one block under the shooting line?
And the bug with the water can be fixed

**Comment by rapus95** [comment]
> So you suggest that the bridge should appeare maybe one block under the shooting line?
> And the bug with the water can be fixed

Maybe even exactly as much below the shooting line as the shoot off point is above the ground. That way you can naturally keep moving.
