### ISSUE TITLE
[Enhancement] Infinity Upgrade that is toggleable

### ISSUE THREAD

**Issue by rapus95** [MrMarnic/ExtraBows#24]
As vanilla infinity requires at least one arrow, that upgrade could do better by requiring no arrow at all. Also I personally don't like it if there are many of these arrow ghosts being in any block around me (somewhat ugly). Thus using no infinity as long as I have arrows and enabling infinity only when I'm out of arrows would be really cool.

**Comment by MrMarnic** [comment]
Sorry but I dont think this will be added, because the infinity enchantment serves the purpose well.
