### ISSUE TITLE
Crash when trying to shoot a bow

### ISSUE THREAD

**Issue by CrossedRhombus1** [MrMarnic/ExtraBows#3]
Playing on a forge server, with a friend, won't let me even charge up a shot, as soon as I right click, the game crashes, however, the server does not. This appears on the launcher:
The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Provider me.marnic.extrabows.common.items.StorageProvider.getCapability() returned null; return LazyOptional.empty() instead!
This is the full log if you would like it instead: https://gist.github.com/CrossedRhombus1/5ed3598dd1c66899a87845532fad0490

**Comment by MrMarnic** [comment]
Which Minecraft and mod version are you using?

**Comment by CrossedRhombus1** [comment]
forge-1.14.13-27.0.50
extrabows-v1.14.3+b6

**Comment by MrMarnic** [comment]
Did you have the world before you installed the mod or did you create a new world?

**Comment by CrossedRhombus1** [comment]
The server did not have a world before installing the mods.

**Comment by OAW61** [comment]
Hello, I have this problem with Java version also...
I see you fixed it for Fabric, could you fix it for Java too ?

Thanks in advance ! I love your mod !

**Comment by MrMarnic** [comment]
Can I send you a test version?

**Comment by MrMarnic** [comment]
Could you also tell me when this happens.

**Comment by OAW61** [comment]
Ok ! Go ahead !

**Comment by OAW61** [comment]
The crash happens when I right click with normal bow (I have arrows in my inventory)

**Comment by OAW61** [comment]
Also I see you made an update but it's weird because I have a Forge version for 1.14.3 and you made it for 1.12.2 but I can't find any version for 1.14.3 so I don't know where I got mine from

**Comment by OAW61** [comment]
My mod file is "extrabows-v1.14.3+b6.jar" for forge
But I see you only have updated for 1.12.2

**Comment by MrMarnic** [comment]
Could you try this version please
https://www.dropbox.com/s/mftoqq96vw3r0v1/extrabows-v1.14.3%20b7.jar?dl=1

And I have set the 1.14.3 Forge version on alpha for now

**Comment by OAW61** [comment]
Ok thanks ! I will try it and tell you if it works !

**Comment by OAW61** [comment]
Hey
I tried the version but it still doesn't work, I still get the crash when using normal bow.

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Provider me.marnic.extrabows.common.items.StorageProvider.getCapability() returned null; return LazyOptional.empty() instead!

 Full log : https://gist.github.com/OAW61/504d78b94b7a7e220db298c11e7a7116

**Comment by MrMarnic** [comment]
That is bad.

Do you have any other mods installed?
Forge version ?
You just use the normal bow with arrows?
Singeplayer/Multiplayer?
DO the other bows work?

**Comment by OAW61** [comment]
Ok, so I have other mods installed. I am on Forge 1.14.3 (27.0.59). Yes, I just use normal bow with arrows. I am on singleplayer. I didn't try the other bows, I can try them if you want.
I'm making a list of my mods

**Comment by OAW61** [comment]
Here is the list of my mods :
https://gist.github.com/OAW61/2531210bd0c24ee7550f156817576a5f

**Comment by OAW61** [comment]
So, I was switched to creative mode to try other bows (diamond for example) but they do the same crash :(

I hope you find the problem and keep doing a great job at modding ! You should be proud ! In the mean time, I will not use bows.

**Comment by MrMarnic** [comment]
Do you have any other mod installed that adds bows?

**Comment by OAW61** [comment]
bow torch mod

**Comment by OAW61** [comment]
torch bow I mean

**Comment by MrMarnic** [comment]
Does the bug also happen if you only have extrabows installed?

**Comment by OAW61** [comment]
I will try without torch bow and tell you

**Comment by OAW61** [comment]
Yes, same crash without torch bow mod.

**Comment by MrMarnic** [comment]
So my last request would be could you try only with ExtraBows installed?

**Comment by OAW61** [comment]
ok !

**Comment by OAW61** [comment]
OMG It works!!
I will try to find the mod that causes the crash.
Thank you so much for your help !

**Comment by MrMarnic** [comment]
Thank you. That would be greate. Because than I can finally fix the bug.

**Comment by OAW61** [comment]
Ok I found it !
The mod causing the problem is "curios" with is needed for "curio of undying" and "curious elytra"
I totally don't need these mods I can do fine so you don't need to fix the crash with this mod.
But if you want, you can !
Thanks for all the help !

**Comment by MrMarnic** [comment]
Could you try this version. It could work.
https://www.dropbox.com/s/8pgtfekm49rpwlk/extrabows-v1.14.3%20b7%20NEW.jar?dl=1

**Comment by MrMarnic** [comment]
I mean with curios

**Comment by OAW61** [comment]
ok

**Comment by OAW61** [comment]
It works ! I didn't really need those mods but it's even better with them !

Thank you so much for your help !
I hope you make great mods !

**Comment by MrMarnic** [comment]
I have uploaded an update.
