### ISSUE TITLE
Teleporting with the Ender Upgrade hurts the player

### ISSUE THREAD

**Issue by tprk77** [MrMarnic/ExtraBows#30]
First of all, nice mod!

Minecraft version: Forge 1.14.4 (1.14.4-forge-28.1.109)
ModLoader version: Forge
Mod Version: v1.14.4 b6

It seems that the player is taking 1 heart of damage on every teleport. This seems to happen regardless of distance or velocity. My best guess is that the player is being put slightly inside the block and taking damage that way. Ideally, the player would never take damage from teleporting.

**Comment by tprk77** [comment]
Actually, I think I'm seeing that this is intentional:

```
player.attackEntityFrom(DamageSource.FALL,2);
```

Would it be possible to make this a configurable option?

**Comment by MrMarnic** [comment]
The ender pearl upgrade damage was removed

**Comment by tprk77** [comment]
Thanks!
