### ISSUE TITLE
[Fabric] Crash on start, Minecraft version 1.15.1 (extrabows-v1.15.1+b1)

### ISSUE THREAD

**Issue by kissedbytherains** [MrMarnic/ExtraBows#32]
Can't start the game, using multimc launcher
0.7.4+build.177 fabric loader version

https://paste.ee/p/282aF

**Comment by kissedbytherains** [comment]
Update:
now using -
1.15.2
0.7.5+build.178 fabric loader
fabric-api-0.4.29+build.290-1.15

Mod differences:
Removed
- bulkyshulkies
- linked storage
- foamfix
- requiem

Added
+ animal net
+ mouse wheelie
+ giftit
+ conveyance

Minecraft starts, but crashes when using a crafting table or crafting from inventory. 

https://paste.ee/p/YHh2P

**Comment by MrMarnic** [comment]
Fixed in latest build
