### ISSUE TITLE
Game crashes when using some items in the End (ExtraBows-v1.15.1 Forge b3)

### ISSUE THREAD

**Issue by BuggyLad** [MrMarnic/ExtraBows#35]
In the End, while using some items like water bucket, flint and steel, ender pearl etc., the game crashes.
ModLoader: Forge-1.15.1-30.0.51
Mod Version: ExtraBows-v1.15.1 Forge b3
Crash reports: https://paste.ee/p/egXbc

**Comment by MrMarnic** [comment]
In which hand was the bow or bucket. Main or Off Hand?

**Comment by BuggyLad** [comment]
Every item was in the main hand.

**Comment by MrMarnic** [comment]
Should be fixed with latest update
