### ISSUE TITLE
Crash when entering the end

### ISSUE THREAD

**Issue by LocalOracularBunny** [MrMarnic/ExtraBows#37]
Version Forge 1.14.4 b8
When I enter the end with this mod installed the server crashes. 
[crash-2020-01-28_14.14.04-server.txt](https://github.com/MrMarnic/ExtraBows/files/4122813/crash-2020-01-28_14.14.04-server.txt)

**Comment by MrMarnic** [comment]
Ok. But could you please test if it happens only with ExtraBows installed because I tried it and the game didn't crash,

**Comment by LocalOracularBunny** [comment]
Ill try that when I get home and let you know.

**Comment by LocalOracularBunny** [comment]
Tested with removing all the other mods and still having the crash. It didn't start until after I defeated the ender dragon so that might have something to do with it? Attached is another crash log.
[crash-2020-02-04_06.35.01-server.txt](https://github.com/MrMarnic/ExtraBows/files/4151748/crash-2020-02-04_06.35.01-server.txt)

**Comment by LocalOracularBunny** [comment]
For further testing i created a brand new single player world. 
Created new world, 
went to the end (without problem)
defeated ender dragon
respawned in overworld
returned to end portal
entered portal
crash.

Seems to work if I enter the end while holding a bow from your mod.

**Comment by MrMarnic** [comment]
Should be fixed with latest update
