### ISSUE TITLE
Bows(including vanilla) dont fire vanilla/mod arrows

### ISSUE THREAD

**Issue by BullerEX** [MrMarnic/ExtraBows#4]
Henlo I have your mod installed alongside with other mods, the bows like regular vanilla or from the stone to emerald bow they only fire normal arrows even If I have special arrows in my inv.
I have other mods that also add more bows to the game and those bows can fire all the arrows so I guess the issue is with your mod(no offense pretty good mod lol)

**Comment by MrMarnic** [comment]
Error will be fixed in the next version

**Comment by MrMarnic** [comment]
Should be fixed in Extra Bows-v1.14.3 Fabric b2

**Comment by BullerEX** [comment]
can I use that version still on MC 1.12.2? Im using that version of the mod in my modpack
