### ISSUE TITLE
Array of issues

### ISSUE THREAD

**Issue by RetroAech** [MrMarnic/ExtraBows#5]
I have the same issues as the other posters, Skeletons are missing bow texture and either just don't have anything in their hands and still continue to shoot, or they have the purple and black missing texture box. Also when they drop a bow its a black and purple box again and when spawned in a normal vanilla bow it works for a few shots then crashes the game.

I exited out of the crash report but I will try to replicate it and post here

**Comment by RetroAech** [comment]
1.14.3 b6, generated the world with the mod installed btw

**Comment by SDUBZ** [comment]
bows dont keep upgrades,also enchants dont stay either and miss textures from vanilla bones

**Comment by MrMarnic** [comment]
Should be fixed in Extra Bows-v1.14.3 Fabric b2
