### ISSUE TITLE
Conflict with tags causes skeletons to not be able to shoot arrows.

### ISSUE THREAD

**Issue by FeonixBrimstone** [MrMarnic/ExtraBows#6]
with the mod installed my server brings up an issue with keys and causes all skeletons to be unable to use their bows.

**Comment by MrMarnic** [comment]
Will be fixed in the next version

**Comment by MrMarnic** [comment]
Should be fixed in Extra Bows-v1.14.3 Fabric b2

**Comment by MrMarnic** [comment]
Should be fixed in Extra Bows-v1.14.3 Fabric b2
