### ISSUE TITLE
creative menu problem

### ISSUE THREAD

**Issue by theuberpony** [MrMarnic/ExtraBows#7]
along with the base bow rendering as a pink and black block, in the creative menu the extra bows tab overrides the first tab with the building blocks. it doesn't move it somewhere else so the only way to find the building blocks is to go into the search tab with everything.

**Comment by KingSavage7** [comment]
Yes, this has been a pain.

**Comment by MrMarnic** [comment]
Will be fixed in the next version

**Comment by MrMarnic** [comment]
Should be fixed in Extra Bows-v1.14.3 Fabric b2
