### ISSUE TITLE
Texture with vanilla bow still bad

### ISSUE THREAD

**Issue by HunterMitchell625** [MrMarnic/ExtraBows#8]
Skeleton or in inventory the vanilla bow texture is still gone.

**Comment by MrMarnic** [comment]
Which version are you using?

**Comment by MrMarnic** [comment]
Because it is working on Fabric 1.14.3 b2

![](https://i.imgur.com/Nji9cjx.png)

**Comment by MrMarnic** [comment]
And Forge 1.14.3 b6

![2019-07-22_06 33 59](https://user-images.githubusercontent.com/42642302/61606483-dbff2680-ac4a-11e9-9319-63e4db97fe20.png)

**Comment by MrMarnic** [comment]
It should be fixed in Extra Bows-v1.14.3 Fabric b3
